Feature/add requests with params
sazanik/library pull request #11
Opened 2022-02-10 13:18 UTC by sazanik

2022-02-10 13:38 UTC, ArturRusak requested changes

2022-02-10 13:38 UTC, ArturRusak commented on src/store/books/asyncActions.ts
> +  snapshot.forEach((docItem) => {
I guess you could use reduce there

2022-02-10 13:38 UTC, ArturRusak commented on src/store/authors/asyncActions.ts
> +const readDocs = async (docsCount?: number): Promise<ReadAuthorsDocsProps> => {
I met it twice, I guess should be moved in utils

2022-02-10 14:04 UTC, sazanik commented on src/store/books/asyncActions.ts
> +  snapshot.forEach((docItem) => {
there it object with forEach method in prototype

2022-02-10 14:05 UTC, sazanik commented on src/components/Table/Table.tsx
> +    dispatch(state[entity].getCollection(pageSize) as any).then(() => {
здесь без any никак, не работает именно с async actions

2022-02-11 07:15 UTC, ArturRusak commented on src/components/Table/Table.tsx
> +    dispatch(state[entity].getCollection(pageSize) as any).then(() => {
code style - means you have problem with code convention,
then should be on a new line.
also your code is hard for reading. because you often uses nested calls

2022-02-11 09:37 UTC, sazanik commented on src/components/Table/Table.tsx
> +    dispatch(state[entity].getCollection(pageSize) as any).then(() => {
I have not found a line wrap rule for one method, only for 2 or more. Therefore temporarily replace on await

2022-02-11 09:41 UTC, merged