connect firebase api
sazanik/library pull request #3
Opened 2022-01-19 11:10 UTC by sazanik

2022-01-19 11:46 UTC, ArturRusak requested changes

2022-01-19 11:46 UTC, ArturRusak commented on src/components/Auth/Form/AuthForm.tsx
> +  const [serverError, setServerError] = useState('');
better to use here null

2022-01-19 11:46 UTC, ArturRusak commented on src/components/Auth/Form/AuthForm.tsx
> +    wrapperAuth(auth, data.email, data.password)
should be implemented with thunk

2022-01-19 11:46 UTC, ArturRusak commented on src/components/DialogBox/DialogBox.tsx
> +  openDialog: boolean;
rename please, read the naming convention again

2022-01-19 11:46 UTC, ArturRusak commented on src/components/DialogBox/DialogBox.tsx
> +  const translate = {
Think about supporting, what will be in case we will add additional entity?
I guess better will be pass title and descriptions as props

2022-01-19 11:46 UTC, ArturRusak commented on src/components/Input/Input.tsx
> +export const Input = forwardRef(
why do you use Textfield here instead of Input ?
Are you sure you need here forwardRef ?

2022-01-19 11:46 UTC, ArturRusak commented on src/i18n/i18n.ts
> +  en: {
try to find more generic approach

2022-01-19 11:46 UTC, ArturRusak commented on src/store/app/appSlice.ts
> +        state.loading = true;
looks awful

2022-01-19 12:26 UTC, sazanik commented on src/components/Auth/Form/AuthForm.tsx
> +  const [serverError, setServerError] = useState('');
fixed

2022-01-19 12:35 UTC, sazanik commented on src/components/DialogBox/DialogBox.tsx
> +  openDialog: boolean;
fixed

2022-01-19 15:17 UTC, sazanik commented on src/components/Auth/Form/AuthForm.tsx
> +    wrapperAuth(auth, data.email, data.password)
fixed

2022-01-20 07:37 UTC, sazanik commented on src/components/DialogBox/DialogBox.tsx
> +  const translate = {
fixed

2022-01-20 07:50 UTC, sazanik commented on src/i18n/i18n.ts
> +  en: {
fixed

2022-01-20 09:24 UTC, sazanik commented on src/store/app/appSlice.ts
> +        state.loading = true;
in work

2022-01-20 11:20 UTC, sazanik commented on src/store/app/appSlice.ts
> +        state.loading = true;
fixed

2022-01-31 14:17 UTC, closed without merging