feature/connect api
sazanik/library pull request #6
Opened 2022-01-21 14:40 UTC by sazanik

2022-01-24 08:11 UTC, ArturRusak requested changes

2022-01-24 08:11 UTC, ArturRusak commented on src/store/users/actions.ts
> +  await signInWithEmailAndPassword(auth, email, password);
bad name

2022-01-24 08:11 UTC, ArturRusak commented on src/components/DialogBox/DialogBox.tsx
> +  const dialogsTranslation = {
pass it as props

2022-01-24 08:11 UTC, ArturRusak commented on src/components/Table/Table.tsx
> +      rowsPerPageOptions={[13]}
move to named const

2022-01-24 08:11 UTC, ArturRusak commented on src/context/AuthContextProvider.tsx
> +    auth.signOut().catch((e) => console.error(e));
should be passed to store

2022-01-24 08:11 UTC, ArturRusak commented on src/screens/BookCard/ScreensBookCard.tsx
> +    if (!book) return;
Don't write in one lien

2022-01-24 08:11 UTC, ArturRusak commented on src/types/enums.ts
> +  FirstName = 'firstName',
use capital letters with Enums

2022-01-24 08:19 UTC, sazanik commented on src/store/users/actions.ts
> +  await signInWithEmailAndPassword(auth, email, password);
it is method firebase API

2022-01-24 12:09 UTC, sazanik commented on src/components/Table/Table.tsx
> +      rowsPerPageOptions={[13]}
fixed

2022-01-24 12:09 UTC, sazanik commented on src/components/DialogBox/DialogBox.tsx
> +  const dialogsTranslation = {
fixed

2022-01-24 12:34 UTC, sazanik commented on src/screens/BookCard/ScreensBookCard.tsx
> +    if (!book) return;
fixed

2022-01-24 12:34 UTC, sazanik commented on src/types/enums.ts
> +  FirstName = 'firstName',
fixed

2022-01-24 12:38 UTC, sazanik commented on src/context/AuthContextProvider.tsx
> +    auth.signOut().catch((e) => console.error(e));
fixed

2022-01-31 07:45 UTC, ArturRusak requested changes

2022-01-31 07:45 UTC, ArturRusak commented on src/store/app/appSlice.ts
> +    stopLoading: (state) => {
why do we need this state? 
also, why do you implement business logic here?

2022-01-31 07:45 UTC, ArturRusak commented on src/store/authors/actions.ts
> +const readDocs = async (): Promise<AuthorProps[]> => {
Write it together with createAsyncThunk or create fabric function.

2022-01-31 07:45 UTC, ArturRusak commented on src/store/authors/authorsSlice.ts
> +        if (author) {
Why do you check here author ?

2022-01-31 07:45 UTC, ArturRusak commented on src/store/authors/authorsSlice.ts
> +        if (id) {
the same

2022-01-31 14:15 UTC, merged